import Head from "next/head";
import Script from "next/script";

export default function Meta({ title }) {
	return (
		<Head>
			<Script async strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=UA-218243418-1"/>
			<Script id="google-analytics" strategy="afterInteractive">
			{` 
				window.dataLayer = window.dataLayer || [];
				function gtag(){
				dataLayer.push(arguments)
				}
				gtag('js', new Date());

				gtag('config', 'UA-218243418-1'); 
				`}
			</Script>

			<title>{title} | Mahipono</title>
			<meta name="description" content="Generated by create next app." />
			<link rel="icon" href="/favicon.png" />
		</Head>
	);
}
