import Head from "next/head";

export default function Meta({ title }) {
	return (
		<Head>
			<script async src="https://www.googletagmanager.com/gtag/js?id=UA-218243418-1"></script>
			<script>
 			 window.dataLayer = window.dataLayer || [];
 			 function gtag(){
			 dataLayer.push(arguments)
			 }
 			 gtag('js', new Date());

  			gtag('config', 'UA-218243418-1');
			</script>

			<title>{title} | Mahipono</title>
			<meta name="description" content="Generated by create next app." />
			<link rel="icon" href="/favicon.png" />
		</Head>
	);
}
