import Head from "next/head";

export default function Meta({ title }) {
	return (
		<Head>
			{/* Google tag (gtag.js) */}
			<script async strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-349SVR4H7K"></script>
			<script id="google-analytics" strategy="afterInteractive">
				{`
				window.dataLayer = window.dataLayer || [];
				function gtag(){dataLayer.push(arguments);}
				gtag('js', new Date());

				gtag('config', 'G-349SVR4H7K');
				`}
			</script>

			<title>{title} | Mahipono</title>
			<meta name="description" content="Generated by create next app." />
			<link rel="icon" href="/favicon.png" />
		</Head>
	);
}
